# action.yml
name: 'Set ENV vars from SSM Path'
description: 'Set ENV vars from SSM Path'
inputs:
  ssm-path:
    description: 'SSM path from which to set Job vars'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ssm-path }}